import { describe, expect, it } from 'vitest'
import {
  decodeBinaryFrame,
  FRAME_COMPRESSED_EVENT,
  FRAME_EVENT,
} from './codec'

// ── WIRE CONTRACT TEST ───────────────────────────────────────────────────
// The fixtures below are base64 of bytes produced by the REAL Python encoder
// (backend/openterm/api/ws_codec.py::encode_event), not hand-crafted here.
// That makes this the only test in the repo that pins the cross-language
// contract: if either side changes framing (endianness, msgpack flavor, the
// zstd threshold), this file fails for both of us. Regenerate with:
//   .venv/bin/python - <<'PY'
//   import sys, base64; sys.path.insert(0,'backend')
//   from openterm.api.ws_codec import encode_event
//   print(base64.b64encode(encode_event('tick:X', {'a':1})).decode())
//   PY

function b64(s: string): ArrayBuffer {
  const bin = atob(s)
  const buf = new Uint8Array(bin.length)
  for (let i = 0; i < bin.length; i++) buf[i] = bin.charCodeAt(i)
  return buf.buffer
}

const SMALL_EVENT =
  'AQAAABN0aWNrOkNSWVBUTzpCVENVU0RUhKVwcmljZctA770QAAAAAKRzaXplyz/QAAAAAAAApHNpZGWjYnV5onRzuTIwMjYtMDEtMDFUMDA6MDA6MDArMDA6MDA='

const COMPRESSED_DEPTH =
  'AwAAABRkZXB0aDpDUllQVE86QlRDVVNEVCi1L/1ghQj9CAA2FTAbwCXLAQ/83SVc/vkPW6AZ/o1LUsokZUoNRvfsMQAkACMAnInzcOYsnINzOZMzDxAODAUMAQrYEA/Va2yIh+q/jMHBBRJs8xgcABAODAMICCgwEDSWKDcvGkuU84vGEuXkRWOJcvHO1Zk6T+fO0jk6tzM7dz7nChIRERER0bZt25IkSZLjOI7jOI7j+P///79oLFGuXjSWKEevLpDg67qu67qu6/r///9XVVVVVRERERERzczMzMzYtm3bIiIiIhKA3KghxCin/Q3gleUQECIwRPlJHk7ycCKP8VJTVWmpqaq01FSVJQ8nuXCShyMOxykgKTsJMiQfCTEUnxhdAK8sKhOjU02NMjE61dSUiZFTTU1R3D1fw5i9njfaVQ=='

describe('ws binary framing (generated by the Python backend)', () => {
  it('decodes a small FRAME_EVENT', () => {
    const { type, topic, payload } = decodeBinaryFrame(b64(SMALL_EVENT))
    expect(type).toBe(FRAME_EVENT)
    expect(topic).toBe('tick:CRYPTO:BTCUSDT')
    expect(payload).toMatchObject({ price: 65000.5, size: 0.25, side: 'buy' })
  })

  it('decodes a >1 KiB payload the backend flipped to FRAME_COMPRESSED_EVENT', () => {
    // This is THE regression test for the ws.ts bug where compressed frames
    // (every depth snapshot) were decoded and then silently dropped because
    // the switch only forwarded FRAME_EVENT.
    const { type, topic, payload } = decodeBinaryFrame(b64(COMPRESSED_DEPTH))
    expect(type).toBe(FRAME_COMPRESSED_EVENT)
    expect(topic).toBe('depth:CRYPTO:BTCUSDT')
    const p = payload as { bids: unknown[]; asks: unknown[] }
    expect(p.bids).toHaveLength(20)
    expect(p.asks).toHaveLength(200)
  })

  it('rejects absurd topic lengths before trusting the u32', () => {
    const bad = new Uint8Array(64)
    const view = new DataView(bad.buffer)
    view.setUint8(0, FRAME_EVENT)
    view.setUint32(1, 0xffffffff) // "topic is 4 GiB long" — no.
    expect(() => decodeBinaryFrame(bad.buffer)).toThrow()
  })

  it('rejects truncated frames', () => {
    expect(() => decodeBinaryFrame(new Uint8Array([1, 0, 0]).buffer)).toThrow()
  })
})
